{"timestamp": "2025-05-02 18:52:31,710", "level": "WARNING", "logger": "celery.worker.consumer.consumer", "message": "consumer: Connection to broker lost. Trying to re-establish the connection...", "path": "/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:378", "service": "RSS News API", "error": {"type": "ConnectionError", "message": "Connection closed by server."}}
{"timestamp": "2025-05-02 18:52:31,726", "level": "ERROR", "logger": "celery.worker.consumer.consumer", "message": "consumer: Cannot connect to redis://localhost:6379/0: Error 61 connecting to localhost:6379. Connection refused..\nTrying again in 2.00 seconds... (1/3)\n", "path": "/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:493", "service": "RSS News API"}
{"timestamp": "2025-05-02 18:52:33,734", "level": "ERROR", "logger": "celery.worker.consumer.consumer", "message": "consumer: Cannot connect to redis://localhost:6379/0: Error 61 connecting to localhost:6379. Connection refused..\nTrying again in 4.00 seconds... (2/3)\n", "path": "/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:493", "service": "RSS News API"}
{"timestamp": "2025-05-02 18:52:37,750", "level": "ERROR", "logger": "celery.worker.consumer.consumer", "message": "consumer: Cannot connect to redis://localhost:6379/0: Error 61 connecting to localhost:6379. Connection refused..\nTrying again in 6.00 seconds... (3/3)\n", "path": "/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:493", "service": "RSS News API"}
{"timestamp": "2025-05-02 18:52:43,762", "level": "CRITICAL", "logger": "celery.worker", "message": "Unrecoverable error: OperationalError('Error 61 connecting to localhost:6379. Connection refused.')", "path": "/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/celery/worker/worker.py:206", "service": "RSS News API", "error": {"type": "OperationalError", "message": "Error 61 connecting to localhost:6379. Connection refused."}}
