{"timestamp": "2025-05-06 14:39:41,441", "level": "CRITICAL", "logger": "celery.worker", "message": "Unrecoverable error: ResponseError('WRONGTYPE Operation against a key holding the wrong kind of value')", "path": "/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/celery/worker/worker.py:206", "service": "RSS News API", "error": {"type": "ResponseError", "message": "WRONGTYPE Operation against a key holding the wrong kind of value"}}
{"timestamp": "2025-05-06 14:41:47,958", "level": "CRITICAL", "logger": "celery.worker", "message": "Unrecoverable error: ResponseError('Command # 1 (LLEN feeds) of pipeline caused error: WRONGTYPE Operation against a key holding the wrong kind of value')", "path": "/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/celery/worker/worker.py:206", "service": "RSS News API", "error": {"type": "ResponseError", "message": "Command # 1 (LLEN feeds) of pipeline caused error: WRONGTYPE Operation against a key holding the wrong kind of value"}}
{"timestamp": "2025-05-06 14:51:59,426", "level": "ERROR", "logger": "celery.beat", "message": "Message Error: Couldn't apply scheduled task fetch-news-every-15-minutes: Command # 1 (LLEN feeds) of pipeline caused error: WRONGTYPE Operation against a key holding the wrong kind of value\n['  File \"/Users/nicolajhansen/dev/personal/terminal-news/.venv/bin/celery\", line 8, in <module>\\n    sys.exit(main())\\n', '  File \"/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/celery/__main__.py\", line 15, in main\\n    sys.exit(_main())\\n', '  File \"/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/celery/bin/celery.py\", line 236, in main\\n    return celery(auto_envvar_prefix=\"CELERY\")\\n', '  File \"/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/click/core.py\", line 1161, in __call__\\n    return self.main(*args, **kwargs)\\n', '  File \"/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/click/core.py\", line 1082, in main\\n    rv = self.invoke(ctx)\\n', '  File \"/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/click/core.py\", line 1697, in invoke\\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\\n', '  File \"/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/click/core.py\", line 1443, in invoke\\n    return ctx.invoke(self.callback, **ctx.params)\\n', '  File \"/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/click/core.py\", line 788, in invoke\\n    return __callback(*args, **kwargs)\\n', '  File \"/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/click/decorators.py\", line 33, in new_func\\n    return f(get_current_context(), *args, **kwargs)\\n', '  File \"/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/celery/bin/base.py\", line 135, in caller\\n    return f(ctx, *args, **kwargs)\\n', '  File \"/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/celery/bin/beat.py\", line 72, in beat\\n    return beat().run()\\n', '  File \"/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/celery/apps/beat.py\", line 84, in run\\n    self.start_scheduler()\\n', '  File \"/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/celery/apps/beat.py\", line 113, in start_scheduler\\n    service.start()\\n', '  File \"/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/celery/beat.py\", line 643, in start\\n    interval = self.scheduler.tick()\\n', '  File \"/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/celery/beat.py\", line 353, in tick\\n    self.apply_entry(entry, producer=self.producer)\\n', '  File \"/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/celery/beat.py\", line 283, in apply_entry\\n    exc, traceback.format_stack(), exc_info=True)\\n']", "path": "/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/celery/beat.py:282", "service": "RSS News API", "error": {"type": "SchedulingError", "message": "Couldn't apply scheduled task fetch-news-every-15-minutes: Command # 1 (LLEN feeds) of pipeline caused error: WRONGTYPE Operation against a key holding the wrong kind of value"}}
{"timestamp": "2025-05-06 14:52:02,578", "level": "CRITICAL", "logger": "celery.worker", "message": "Unrecoverable error: ResponseError('Command # 1 (LLEN feeds) of pipeline caused error: WRONGTYPE Operation against a key holding the wrong kind of value')", "path": "/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/celery/worker/worker.py:206", "service": "RSS News API", "error": {"type": "ResponseError", "message": "Command # 1 (LLEN feeds) of pipeline caused error: WRONGTYPE Operation against a key holding the wrong kind of value"}}
{"timestamp": "2025-05-06 15:36:26,691", "level": "CRITICAL", "logger": "celery.worker", "message": "Unrecoverable error: ResponseError('WRONGTYPE Operation against a key holding the wrong kind of value')", "path": "/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/celery/worker/worker.py:206", "service": "RSS News API", "error": {"type": "ResponseError", "message": "WRONGTYPE Operation against a key holding the wrong kind of value"}}
{"timestamp": "2025-05-06 17:02:56,886", "level": "CRITICAL", "logger": "celery.worker", "message": "Unrecoverable error: ResponseError('WRONGTYPE Operation against a key holding the wrong kind of value')", "path": "/Users/nicolajhansen/dev/personal/terminal-news/.venv/lib/python3.13/site-packages/celery/worker/worker.py:206", "service": "RSS News API", "error": {"type": "ResponseError", "message": "WRONGTYPE Operation against a key holding the wrong kind of value"}}
